### PR TITLE
Added UX Burlington to June 2017

### PR DESCRIPTION
**Pull request by DaveLindberg**
Added a new entry for the UXBurlington event.

### CODE REVIEW

**Comment by benmvp** [comment]
Thanks for this! It looks like on the website, that it's "UX Burlington" and not "UXBurlington".

Could you add in the space please? 😄

**Comment by DaveLindberg** [comment]
Done.

**Comment by benmvp** [comment]
I don't think you pushed anything?

**Comment by DaveLindberg** [comment]
Oops. Sorry, try now.

**Comment by benmvp** [comment]
Thanks again!

**Pull request merged**
